name: Build Perl Jupyter container

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List files (debug)
        run: |
          pwd
          ls -la
          ls -la perl-jupyter-podman || true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push)
        uses: docker/build-push-action@v5
        with:
            context: .
            file: perl-jupyter-podman/Containerfile   # 👈 ruta explícita
            push: false
            tags: perl-jupyter:latest
